# Generated by Django 5.0.2 on 2024-03-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreviews_delete_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='parent',
        ),
    ]
