# Generated by Django 5.0.2 on 2024-03-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productreviews_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productreviews'),
        ),
    ]
