# Generated by Django 5.0.2 on 2024-03-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productreviews_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReviews',
        ),
    ]
