# Generated by Django 5.0.2 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_delivery_date_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Delivery'),
        ),
    ]
